name: Install
description: Install Node.js, pnpm, and dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        cache: true

    - name: Install Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: .nvmrc

    - name: Install Dependencies
      shell: bash
      env:
        # Skip Husky installation.
        # See: https://github.com/typicode/husky/blob/ec10d87db/index.js#L9
        HUSKY: '0'
      run: pnpm i
