name: Install
description: Install Node.js, pnpm, and dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      with:
        cache: true

    - name: Install Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: .nvmrc

    - name: Install Dependencies
      shell: bash
      env:
        # Skip Husky installation.
        # See: https://github.com/typicode/husky/blob/ec10d87db/index.js#L9
        HUSKY: '0'
      run: pnpm i
