name: Changeset

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize
    branches:
      - main
      - next

permissions: {}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  require-changeset:
    name: Require Changeset
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Skip opted out PRs, and release PRs
    if: |
      ! contains(github.event.pull_request.labels.*.name, 'skip changelog') &&
      ! (github.event.pull_request.title == 'chore(release): publish' && github.event.pull_request.user.login == 'github-actions[bot]') &&
      ! (github.event.pull_request.user.login == 'dependabot[bot]')

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Dependencies
        uses: ./.github/actions/install

      # Returns exit code 1 when there are changes without changesets attached to them.
      # See: https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md#blocking
      - name: Run Changesets
        run: pnpm changeset status --since origin/${{ github.event.pull_request.base.ref }}

  disallow-major-release:
    name: Disallow Major Release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Block major releases only on main, allow on next.
    # Skip release & dependabot PRs.
    if: |
      github.event.pull_request.base.ref == 'main' &&
      ! (github.event.pull_request.title == 'chore(release): publish' && github.event.pull_request.user.login == 'github-actions[bot]') &&
      ! (github.event.pull_request.user.login == 'dependabot[bot]')

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Dependencies
        uses: ./.github/actions/install

      - name: Check for Major Changeset
        run: |
          pnpm changeset status --since origin/main --output=./.changeset-status.json &> /dev/null || true

          if [ -f ./.changeset-status.json ]; then
            node .github/scripts/check-major-version.ts ./.changeset-status.json
          fi
