name: Sync next branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: next
          fetch-depth: 0

      - name: Rebase onto main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git rebase origin/main

      - name: Force push
        run: git push --force-with-lease
